workflow_name: "text_2_speech_censoring"
workflow_version: "0.0.1"
environment_variables:
  - key: "ENV_VAR_1"
    value: "value_1"
iam_policy_file: "iam_policy.json"
home_region:
  provider: "aws"
  region: "us-east-1"
estimated_invocations_per_month: 1000000
constraints:
  hard_resource_constraints: # None for none
    cost:
      type: "absolute" # Absolute value as 'absolute' (in USD) or Percentage from deployment at home regions as 'relative' (In fractions such as 1.1)
      value: 100
    runtime:
      type: "absolute"
      value: 100
    carbon:
      type: "absolute"
      value: 100
  soft_resource_constraints: # None for none
    cost: null
    runtime: null
    carbon: null
  priority_order:
    - cost
    - runtime
    - carbon
regions_and_providers: # Either the user specify only allowed regions (which will override everything else)
  allowed_regions:
    - provider: "aws"
      region: "us-east-1"
    - provider: "aws"
      region: "us-east-2"
    - provider: "aws"
      region: "us-west-1"
    - provider: "aws"
      region: "us-west-2"
  disallowed_regions:
  providers:
    aws:
      config:
        timeout: 60
        memory: 128
        additional_docker_commands:
          - "yum update -y"
          - "yum install -y tar gzip"
          - "yum install -y xz"
          - "curl https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz > /tmp/ffmpeg-release.tar.xz"
          - "tar xvf /tmp/ffmpeg-release.tar.xz -C /opt"
          - "mv /opt/ffmpeg-* /opt/ffmpeg"
          - "cd /opt/ffmpeg"
          - "mv model /usr/local/share"
          - "mv ffmpeg ffprobe qt-faststart /usr/local/bin"
          - "rm /tmp/ffmpeg-release.tar.xz"
