workflow_name: "text_2_speech_censoring"
workflow_version: "0.0.1"
iam_policy_file: "iam_policy.json"
home_region:
  provider: "aws"
  region: "us-east-1"
estimated_invocations_per_month: 1000000
constraints:
  hard_resource_constraints:
    cost: null
    runtime: null
    carbon: null
  soft_resource_constraints:
    cost: null
    runtime: null
    carbon: null
  priority_order:
    - carbon
    - cost
    - runtime
regions_and_providers:
  allowed_regions:
    - provider: "aws"
      region: "us-east-1"
    - provider: "aws"
      region: "us-west-1"
    - provider: "aws"
      region: "us-west-2"
    - provider: "aws"
      region: "ca-central-1"
  disallowed_regions:
  providers:
    aws:
      config:
        timeout: 300
        memory: 1024
        additional_docker_commands:
          - "yum update -y"
          - "yum install -y tar gzip"
          - "yum install -y xz"
          - "curl https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz > /tmp/ffmpeg-release.tar.xz"
          - "tar xvf /tmp/ffmpeg-release.tar.xz -C /opt"
          - "mv /opt/ffmpeg-* /opt/ffmpeg"
          - "cd /opt/ffmpeg"
          - "mv model /usr/local/share"
          - "mv ffmpeg ffprobe qt-faststart /usr/local/bin"
          - "rm /tmp/ffmpeg-release.tar.xz"
